-- 🌟 Exercise 1 : Items And Customers 
-- CREATE TABLE items(
-- 	id SERIAL PRIMARY KEY,
-- 	name VARCHAR (50) NOT NULL, 
-- 	price INTEGER NOT NULL
-- )
-- SELECT*FROM items

-- CREATE TABLE customers(
-- 	id SERIAL PRIMARY KEY,
-- 	fisrt_name VARCHAR(100)	NOT NULL,
-- 	last_name VARCHAR(100) NOT NULL
-- 	)
-- 	SELECT*FROM customers
-- INSERT INTO items(name,price) VALUES('small desk',100)
-- INSERT INTO items(name,price) VALUES('Large desk',300);
-- INSERT INTO items(name,price) VALUES('fan',80)

-- INSERT INTO customers(fisrt_name,last_name) VALUES('Greg','Jones');
-- INSERT INTO customers(fisrt_name,last_name) VALUES('Sandra','Jones');
-- INSERT INTO customers(fisrt_name,last_name) VALUES('Scott','Scott');
-- INSERT INTO customers(fisrt_name,last_name) VALUES('trevor','Green');
-- INSERT INTO customers(fisrt_name,last_name) VALUES('Melanie','Johnson');
-- SELECT*FROM customers
-- SELECT * FROM items WHERE price > 80;
-- SELECT * FROM items WHERE price <= 300;
-- SELECT * FROM customers WHERE last_name='smith';
-- SELECT * FROM customers WHERE first_name='Jones';
-- SELECT * FROM customers WHERE first_name!='Scott';